# Generated by Django 5.0.7 on 2024-07-19 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('photo_url', models.TextField(blank=True)),
                ('is_add', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TelegramChanell',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('now_parsing', models.BooleanField(default=False)),
                ('frequency', models.BigIntegerField(default=1800)),
            ],
        ),
        migrations.CreateModel(
            name='FinalMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('message', models.TextField()),
                ('date', models.DateTimeField()),
                ('last_messages', models.ManyToManyField(to='fetcher.lastmessages', verbose_name='Из каких сообщений был составлен пост')),
            ],
        ),
        migrations.AddField(
            model_name='lastmessages',
            name='chanell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fetcher.telegramchanell'),
        ),
    ]
