# Generated by Django 5.0.7 on 2024-07-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lastmessages',
            old_name='chanell',
            new_name='channel',
        ),
    ]
