# Generated by Django 5.0.7 on 2024-07-21 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fetcher', '0003_remove_lastmessages_photo_url_lastmessages_media_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastmessages',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
